Fix adoint cylindrical
g-adopt/g-adopt pull request #33
Opened 2023-10-11 02:53 UTC by sghelichkhani

This PR fixes an inconsistency in defining the strain-rate for non-linear cases. The definition of `forward.py` currently uses an additional factor of $\sqrt{1/2}$, that should actually appear in the definition for `epsii`. 

To make the two scripts consistent, and also the same as the original scripts for running the adoints we are now using a higher `sigma_y`.

2023-10-11 03:04 UTC, drhodrid requested changes
I think it's worth adding a short comment next to your definitions of epsii of why you are including the factor of 0.5 (for clarity - because this is different to how we have it in the visco-plastic demo, for example). You should also perhaps say a little about where the 1.41 and 2.82 come from (a scaling from a sqrt(2) error - right)? Fianlly - remove adjoint_spherical_test directory (looks like you just did!).

2023-10-11 03:06 UTC, sghelichkhani commented
Note that this also fixes an issue with loading mesh from `Checkpoint230.h5`, whereas this should load `Checkpoint_State.h5` to preserve the partitioning information from the forward run.

2023-10-11 03:09 UTC, angus-g commented on demos/adjoint_2d_cylindrical/forward.py
> +    sigma_y = 1.4142e4 + 2.8284e5 * (rmax - r)
Should these be e.g. `1e4 * sqrt(2)` and `2e5 * sqrt(2)` or something instead of just floats?

2023-10-11 04:19 UTC, sghelichkhani commented
> I think it's worth adding a short comment next to your definitions of epsii of why you are including the factor of 0.5 (for clarity - because this is different to how we have it in the visco-plastic demo, for example). You should also perhaps say a little about where the 1.41 and 2.82 come from (a scaling from a sqrt(2) error - right)? Fianlly - remove adjoint_spherical_test directory (looks like you just did!).

Yeah thanks! I got rid of an additional factor of 2 (I don't know why I thought that's how we define `epsii`). The values are consistent with Coltice et. al 2017: We use a surface yield stress, its depth derivative of 2e4, and 4e5, compared to 2e4 and 2.5e5 used in Coltice etl al. I have now added a reference there. 

Also counting for the additional factor of 2, we don't need to use floats anymore.

2023-10-11 04:23 UTC, stephankramer commented on demos/adjoint_2d_cylindrical/forward.py
> +    # yeild stress and its depth dependence
```suggestion
    # yield stress and its depth dependence
```

2023-10-11 09:27 UTC, drhodrid commented
OK - so this inverse run now fails when I run it (KSP_DIVERGED_MAX_IT). It turns out that your forward and adjoint models are now inconsistent again in the definitions of epsII. This needs to be fixed. Could you also ensure that the differences in forward.py and inverse.py are solely those arising from the addition of the adjoint related functionality? For example, at the moment, some comments are inconsistent and the ordering of some things seems a little different too (although the latter maybe required - I'm not sure). This makes things harder to debug (e.g. diffs highlight things that shouldn't be different). So perhaps use meld or similar to highlight the differences, and line things up better.

2023-10-11 09:34 UTC, angus-g commented
Suggests that maybe the two should use the same code (inherit the same function)… Then it’s not as prone to manual errors.

Also, given the checkpoint file was renamed, does the file in Git LFS need to be renamed too?

2023-10-12 01:36 UTC, sghelichkhani commented
> OK - so this inverse run now fails when I run it (KSP_DIVERGED_MAX_IT). It turns out that your forward and adjoint models are now inconsistent again in the definitions of epsII. This needs to be fixed. Could you also ensure that the differences in forward.py and inverse.py are solely those arising from the addition of the adjoint related functionality? For example, at the moment, some comments are inconsistent and the ordering of some things seems a little different too (although the latter maybe required - I'm not sure). This makes things harder to debug (e.g. diffs highlight things that shouldn't be different). So perhaps use meld or similar to highlight the differences, and line things up better.

@drhodrid  Hmm... I am not sure what you mean with inconsistency.  Might be you had not pull the changes? The two files were originally different after the original PR. Now  they are as similar as necessary. 

@angus-g Yeah! It would make sense to inherit to ensure consistency. But maybe it's a bit of an overkill for a synthetic test?

Re checkpointfile: No. Renaming of the checkpoint file in `inverse.py` ensures that we use the same partitioning that is used for the reference fields. Currently we load the mesh from `Checkpoint230.h5` but then load the fields from `Checkpoint_State.h5`. So we are not being consistent. By using `Checkpoint_State.h5` we stay consistent.

2023-10-12 04:52 UTC, drhodrid commented
Thanks @sghelichkhani - this now runs for me and things look sensible. I'm happy to approve (and we can revisit @angus-g comment about the inverse code inheriting the forward model at a later date).

2023-10-12 04:52 UTC, drhodrid approved these changes

2023-10-12 04:55 UTC, merged